// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoMiusike.Data;

namespace ProyectoMiusike.Data.Migrations
{
    [DbContext(typeof(WindAppDBContext))]
    [Migration("20200107214140_DefensaInitail")]
    partial class DefensaInitail
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectoMiusike.Data.Entity.ArtistaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("biografia");

                    b.Property<int>("edad");

                    b.Property<string>("imgPath");

                    b.Property<string>("nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("ProyectoMiusike.Data.Entity.CacionEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ArtistaId");

                    b.Property<float>("Duracio");

                    b.Property<string>("Genero")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.Property<int>("Ventas");

                    b.Property<int>("Votacion");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId");

                    b.ToTable("Caciones");
                });

            modelBuilder.Entity("ProyectoMiusike.Data.Entity.CacionEntity", b =>
                {
                    b.HasOne("ProyectoMiusike.Data.Entity.ArtistaEntity", "Artista")
                        .WithMany("Canciones")
                        .HasForeignKey("ArtistaId");
                });
#pragma warning restore 612, 618
        }
    }
}
